version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app

  cypress:
    image: cypress/included
    volumes:
      - .:/app
    depends_on:
      - vue-app
    entrypoint: ["npx", "cypress", "run"]
